apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pp
  annotations:
    github.com/project-slug: jj-scoll/pp
    datadoghq.com/dashboard-url: https://p.datadoghq.com/sb/bc3feaca-a64f-11ed-9d7c-da7ad0900002-f25984d422baa25dbf12a6045d43e603
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://google.com
      title: Google
      icon: dashboard
spec:
  type: service
  lifecycle: unknown
  owner: jj-scoll
